name: CLI validations

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.14
        uses: actions/setup-python@v4
        with:
          python-version: "3.14"
      - uses: actions/cache@v4
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install system dependencies
        run: |
          sudo apt update && sudo apt install -y graphviz graphviz-dev
      - name: Install Python dependencies
        run: |
          python3 -m pip install -v --upgrade pip
          python3 -m pip install -vv -e .[tests]
      - name: Test with own validation script
        run: |
          python3 -m pytest -vv tests/validate_cli.py
