# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package to TestPyPI

on: 
  push:
    branches: [main]
    tags:
      - '**'
      
permissions:
  contents: read
  
jobs:
  build-n-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://pypi.org/project/SLAMBUC/
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install build --user
      - name: Build a binary wheel and a source tarball
        run: python3 -m build --sdist --wheel --outdir dist/ .
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        #if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
          verbose: true
          print-hash: true
