name: SLAMBUC algorithm tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install system dependencies
      run: |
        sudo apt update && sudo apt install -y graphviz graphviz-dev
    - name: Install Python dependencies
      run: |
        python3.10 -m pip install -v --upgrade pip
        python3.10 -m pip install -v -U -r requirements_py3.10.txt
        python3.10 -m pip install -vv -e .
    - name: Test with pytest
      run: |
        cd tests && python3.10 -m pytest -vv .
