name: pytest-py3.13

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"
      - uses: actions/cache@v4
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install system dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y graphviz libgraphviz-dev pkg-config glpk-utils
      - name: Install Python dependencies
        run: |
          python3.13 -m pip install -v --upgrade pip
          python3.13 -m pip install -v -U -r requirements.txt
          python3.13 -m pip install -vv -e .
      - name: Test with pytest
        run: |
          python3.13 -m pytest -vv tests/
