# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test SLAMBUC algorithms

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        apt update && apt install graphviz graphviz-dev
        python3.11 -m pip install --upgrade pip
        python3.11 -m pip install -U -r requirements.txt
        python3.11 -m pip install --ignore-requires-python --no-deps -e .
    - name: Test with own validation script
      run: |
        python3.11 test/validate_algs.py
